// 빌드 타임 prebuild — cases 디렉토리 → 정적 모듈 dump
// (1) frontmatter+content 를 cases.generated.ts 로 dump (런타임 fs 호출 회피)
// (2) MDX 본문을 _compiled.jsx 로 컴파일 (Cloudflare Workers V8 isolate 의 eval 차단 회피)
// (3) slug → 컴파일된 컴포넌트 매핑을 cases.compiled.ts 로 emit
import fs from "node:fs/promises";
import path from "node:path";
import matter from "gray-matter";
import { compile } from "@mdx-js/mdx";
import remarkGfm from "remark-gfm";
import rehypeSlug from "rehype-slug";
import rehypeAutolinkHeadings from "rehype-autolink-headings";

const CWD = process.cwd();
const CASES_DIR = path.join(CWD, "src/features/work/cases");
const LIB_DIR = path.join(CWD, "src/features/work/lib");
const GENERATED_FILE = path.join(LIB_DIR, "cases.generated.ts");
const COMPILED_MAP_FILE = path.join(LIB_DIR, "cases.compiled.ts");

const entries = await fs.readdir(CASES_DIR, { withFileTypes: true });
const slugs = entries
  .filter((e) => e.isDirectory() && !e.name.startsWith("_"))
  .map((e) => e.name);

const cases = await Promise.all(
  slugs.map(async (slug) => {
    const filePath = path.join(CASES_DIR, slug, "index.mdx");
    const raw = await fs.readFile(filePath, "utf8");
    const { data, content } = matter(raw);

    const compiled = await compile(content, {
      jsx: true,
      outputFormat: "program",
      remarkPlugins: [remarkGfm],
      rehypePlugins: [
        rehypeSlug,
        [
          rehypeAutolinkHeadings,
          {
            behavior: "wrap",
            properties: { className: ["heading-anchor"] },
          },
        ],
      ],
    });

    const compiledPath = path.join(CASES_DIR, slug, "_compiled.jsx");
    await fs.writeFile(
      compiledPath,
      `// AUTO-GENERATED by scripts/build-cases.mjs — do not edit\n${String(compiled)}`,
    );

    return { slug, data, content };
  }),
);

// gray-matter 가 YAML 날짜를 Date 객체로 파싱 — Date.toJSON 이 ISO datetime 을 만들기 전에
// 미리 트리를 순회하며 YYYY-MM-DD 문자열로 정규화 (Zod schema 가 YYYY-MM-DD 만 허용)
function normalizeDates(value) {
  if (value instanceof Date) return value.toISOString().slice(0, 10);
  if (Array.isArray(value)) return value.map(normalizeDates);
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).map(([k, v]) => [k, normalizeDates(v)]),
    );
  }
  return value;
}

const generatedOut = `// AUTO-GENERATED by scripts/build-cases.mjs — do not edit
export type GeneratedCase = {
  slug: string;
  data: Record<string, unknown>;
  content: string;
};

export const generatedCases: GeneratedCase[] = ${JSON.stringify(normalizeDates(cases), null, 2)};
`;

await fs.writeFile(GENERATED_FILE, generatedOut);

// slug → 컴파일된 MDX 컴포넌트 매핑
const toIdent = (slug) =>
  slug.replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase()).replace(/^./, (c) => c.toUpperCase());

const imports = cases
  .map(({ slug }) => `import ${toIdent(slug)} from "../cases/${slug}/_compiled.jsx";`)
  .join("\n");

const entriesOut = cases
  .map(({ slug }) => `  "${slug}": ${toIdent(slug)} as MDXContentComponent,`)
  .join("\n");

const compiledMapOut = `// AUTO-GENERATED by scripts/build-cases.mjs — do not edit
import type { ComponentType } from "react";
import type { MDXComponents } from "mdx/types";
${imports}

type MDXContentComponent = ComponentType<{ components?: MDXComponents }>;

export const compiledCases: Record<string, MDXContentComponent> = {
${entriesOut}
};
`;

await fs.writeFile(COMPILED_MAP_FILE, compiledMapOut);

console.log(
  `✓ generated ${cases.length} cases\n  → ${path.relative(CWD, GENERATED_FILE)}\n  → ${path.relative(CWD, COMPILED_MAP_FILE)}\n  → ${cases.length} × cases/<slug>/_compiled.jsx`,
);
